[package]
name = "circuit"
type = "bin"
authors = [""]

[dependencies]
jwt = { tag = "v0.4.4", git = "https://github.com/zkemail/noir-jwt" }
poseidon = { tag = "v0.1.1", git = "https://github.com/noir-lang/poseidon" }